SAMPLE_PER_RELATION: 1 # samples/bags for each predicates , total train predicates = 100
XML_FILE_PATH_VrRVG: VrR-VG # xml files for VrRVG
NPY_FILE_PATH: all_vg_frcnn
DATASET: VrRVG # options are VrRVG and VG150 
VREncoder_Net_Checkpoint: VR_encoder_checkpoints/checkpoint_2.pt
train_predicates_path : data/vrrvg_predicates_train.json
VREncoderEmbeddings: VTransE # VTransE and VRConcat
VREncoderConfig: VR_Encoder/configs/model_config.yaml
