per_gpu_train_batch_size: 64
xml_file_path: VrR-VG # path to vrr-vg xml files directory
npy_file_path: all_vg_frcnn # path to faster r-cnn features directory
saved_dir: saved_vr_encoder_relations # path to save vr during training
train_predicates_path: data/vrrvg_predicates_train.json 
saved_vtranse_input: True # save relations while training
training_split_ratio : 0.8